package exchange

// CreativeAttribute are some attribute predefined by iab
type CreativeAttribute int

const (
	// CreativeAttributeAudioAdAutoPlay AudioAdAutoPlay attribute
	CreativeAttributeAudioAdAutoPlay CreativeAttribute = iota + 1
	// CreativeAttributeAudioAdUserInitiated AudioAdUserInitiated attribute
	CreativeAttributeAudioAdUserInitiated
	// CreativeAttributeExpandableAuto ExpandableAuto attribute
	CreativeAttributeExpandableAuto
	// CreativeAttributeExpandableUserInitiatedClick ExpandableUserInitiatedClick attribute
	CreativeAttributeExpandableUserInitiatedClick
	// CreativeAttributeExpandableUserInitiatedRollover ExpandableUserInitiatedRollover attribute
	CreativeAttributeExpandableUserInitiatedRollover
	// CreativeAttributeInBannerVideoAdAutoPlay InBannerVideoAdAutoPlay attribute
	CreativeAttributeInBannerVideoAdAutoPlay
	// CreativeAttributeInBannerVideoAdUserInitiated InBannerVideoAdUserInitiated attribute
	CreativeAttributeInBannerVideoAdUserInitiated
	// CreativeAttributePop Pop attribute
	CreativeAttributePop
	// CreativeAttributeProvocativeOrSuggestiveImagery ProvocativeOrSuggestiveImagery attribute
	CreativeAttributeProvocativeOrSuggestiveImagery
	// CreativeAttributeExtremeAnimation ExtremeAnimation attribute
	CreativeAttributeExtremeAnimation
	// CreativeAttributeSurveys Surveys attribute
	CreativeAttributeSurveys
	// CreativeAttributeTextOnly TextOnly attribute
	CreativeAttributeTextOnly
	// CreativeAttributeUserInitiated UserInitiated attribute
	CreativeAttributeUserInitiated
	// CreativeAttributeWindowsDialogOrAlert WindowsDialogOrAlert attribute
	CreativeAttributeWindowsDialogOrAlert
	// CreativeAttributeHasAudioWithPlayer HasAudioWithPlayer attribute
	CreativeAttributeHasAudioWithPlayer
	// CreativeAttributeAdProvidesSkipButton AdProvidesSkipButton attribute
	CreativeAttributeAdProvidesSkipButton
	// CreativeAttributeAdobeFlash AdobeFlash attribute
	CreativeAttributeAdobeFlash
)
