// Code generated by MockGen. DO NOT EDIT.
// Source: clickyab.com/exchange/octopus/exchange (interfaces: Impression,Demand,Publisher,Location,Supplier,BidResponse,Bid,AdDetail,BidRequest,Banner,Device,Inventory,Site,App,Native,User,Video)

package mock_exchange

import (
	exchange "clickyab.com/exchange/octopus/exchange"
	context "context"
	gomock "github.com/golang/mock/gomock"
	io "io"
	http "net/http"
	reflect "reflect"
	time "time"
)

// MockImpression is a mock of Impression interface
type MockImpression struct {
	ctrl     *gomock.Controller
	recorder *MockImpressionMockRecorder
}

// MockImpressionMockRecorder is the mock recorder for MockImpression
type MockImpressionMockRecorder struct {
	mock *MockImpression
}

// NewMockImpression creates a new mock instance
func NewMockImpression(ctrl *gomock.Controller) *MockImpression {
	mock := &MockImpression{ctrl: ctrl}
	mock.recorder = &MockImpressionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockImpression) EXPECT() *MockImpressionMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockImpression) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockImpressionMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockImpression)(nil).Attributes))
}

// Banner mocks base method
func (_m *MockImpression) Banner() exchange.Banner {
	ret := _m.ctrl.Call(_m, "Banner")
	ret0, _ := ret[0].(exchange.Banner)
	return ret0
}

// Banner indicates an expected call of Banner
func (_mr *MockImpressionMockRecorder) Banner() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Banner", reflect.TypeOf((*MockImpression)(nil).Banner))
}

// BidFloor mocks base method
func (_m *MockImpression) BidFloor() float64 {
	ret := _m.ctrl.Call(_m, "BidFloor")
	ret0, _ := ret[0].(float64)
	return ret0
}

// BidFloor indicates an expected call of BidFloor
func (_mr *MockImpressionMockRecorder) BidFloor() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BidFloor", reflect.TypeOf((*MockImpression)(nil).BidFloor))
}

// CID mocks base method
func (_m *MockImpression) CID() string {
	ret := _m.ctrl.Call(_m, "CID")
	ret0, _ := ret[0].(string)
	return ret0
}

// CID indicates an expected call of CID
func (_mr *MockImpressionMockRecorder) CID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CID", reflect.TypeOf((*MockImpression)(nil).CID))
}

// Currency mocks base method
func (_m *MockImpression) Currency() string {
	ret := _m.ctrl.Call(_m, "Currency")
	ret0, _ := ret[0].(string)
	return ret0
}

// Currency indicates an expected call of Currency
func (_mr *MockImpressionMockRecorder) Currency() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Currency", reflect.TypeOf((*MockImpression)(nil).Currency))
}

// ID mocks base method
func (_m *MockImpression) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockImpressionMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockImpression)(nil).ID))
}

// Native mocks base method
func (_m *MockImpression) Native() exchange.Native {
	ret := _m.ctrl.Call(_m, "Native")
	ret0, _ := ret[0].(exchange.Native)
	return ret0
}

// Native indicates an expected call of Native
func (_mr *MockImpressionMockRecorder) Native() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Native", reflect.TypeOf((*MockImpression)(nil).Native))
}

// Secure mocks base method
func (_m *MockImpression) Secure() bool {
	ret := _m.ctrl.Call(_m, "Secure")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Secure indicates an expected call of Secure
func (_mr *MockImpressionMockRecorder) Secure() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Secure", reflect.TypeOf((*MockImpression)(nil).Secure))
}

// Type mocks base method
func (_m *MockImpression) Type() exchange.ImpressionType {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(exchange.ImpressionType)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockImpressionMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Type", reflect.TypeOf((*MockImpression)(nil).Type))
}

// Video mocks base method
func (_m *MockImpression) Video() exchange.Video {
	ret := _m.ctrl.Call(_m, "Video")
	ret0, _ := ret[0].(exchange.Video)
	return ret0
}

// Video indicates an expected call of Video
func (_mr *MockImpressionMockRecorder) Video() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Video", reflect.TypeOf((*MockImpression)(nil).Video))
}

// MockDemand is a mock of Demand interface
type MockDemand struct {
	ctrl     *gomock.Controller
	recorder *MockDemandMockRecorder
}

// MockDemandMockRecorder is the mock recorder for MockDemand
type MockDemandMockRecorder struct {
	mock *MockDemand
}

// NewMockDemand creates a new mock instance
func NewMockDemand(ctrl *gomock.Controller) *MockDemand {
	mock := &MockDemand{ctrl: ctrl}
	mock.recorder = &MockDemandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockDemand) EXPECT() *MockDemandMockRecorder {
	return _m.recorder
}

// Bill mocks base method
func (_m *MockDemand) Bill(_param0 context.Context, _param1 int64, _param2 string) {
	_m.ctrl.Call(_m, "Bill", _param0, _param1, _param2)
}

// Bill indicates an expected call of Bill
func (_mr *MockDemandMockRecorder) Bill(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Bill", reflect.TypeOf((*MockDemand)(nil).Bill), arg0, arg1, arg2)
}

// CallRate mocks base method
func (_m *MockDemand) CallRate() int {
	ret := _m.ctrl.Call(_m, "CallRate")
	ret0, _ := ret[0].(int)
	return ret0
}

// CallRate indicates an expected call of CallRate
func (_mr *MockDemandMockRecorder) CallRate() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CallRate", reflect.TypeOf((*MockDemand)(nil).CallRate))
}

// EndPoint mocks base method
func (_m *MockDemand) EndPoint() string {
	ret := _m.ctrl.Call(_m, "EndPoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// EndPoint indicates an expected call of EndPoint
func (_mr *MockDemandMockRecorder) EndPoint() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EndPoint", reflect.TypeOf((*MockDemand)(nil).EndPoint))
}

// ExcludedSuppliers mocks base method
func (_m *MockDemand) ExcludedSuppliers() []string {
	ret := _m.ctrl.Call(_m, "ExcludedSuppliers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ExcludedSuppliers indicates an expected call of ExcludedSuppliers
func (_mr *MockDemandMockRecorder) ExcludedSuppliers() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ExcludedSuppliers", reflect.TypeOf((*MockDemand)(nil).ExcludedSuppliers))
}

// GetBidResponse mocks base method
func (_m *MockDemand) GetBidResponse(_param0 context.Context, _param1 *http.Response, _param2 exchange.Supplier) (exchange.BidResponse, error) {
	ret := _m.ctrl.Call(_m, "GetBidResponse", _param0, _param1, _param2)
	ret0, _ := ret[0].(exchange.BidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBidResponse indicates an expected call of GetBidResponse
func (_mr *MockDemandMockRecorder) GetBidResponse(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetBidResponse", reflect.TypeOf((*MockDemand)(nil).GetBidResponse), arg0, arg1, arg2)
}

// GetTimeout mocks base method
func (_m *MockDemand) GetTimeout() time.Duration {
	ret := _m.ctrl.Call(_m, "GetTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetTimeout indicates an expected call of GetTimeout
func (_mr *MockDemandMockRecorder) GetTimeout() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetTimeout", reflect.TypeOf((*MockDemand)(nil).GetTimeout))
}

// Handicap mocks base method
func (_m *MockDemand) Handicap() int64 {
	ret := _m.ctrl.Call(_m, "Handicap")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Handicap indicates an expected call of Handicap
func (_mr *MockDemandMockRecorder) Handicap() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Handicap", reflect.TypeOf((*MockDemand)(nil).Handicap))
}

// HasLimits mocks base method
func (_m *MockDemand) HasLimits() bool {
	ret := _m.ctrl.Call(_m, "HasLimits")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasLimits indicates an expected call of HasLimits
func (_mr *MockDemandMockRecorder) HasLimits() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "HasLimits", reflect.TypeOf((*MockDemand)(nil).HasLimits))
}

// Name mocks base method
func (_m *MockDemand) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockDemandMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockDemand)(nil).Name))
}

// Provide mocks base method
func (_m *MockDemand) Provide(_param0 context.Context, _param1 exchange.BidRequest, _param2 chan exchange.BidResponse) {
	_m.ctrl.Call(_m, "Provide", _param0, _param1, _param2)
}

// Provide indicates an expected call of Provide
func (_mr *MockDemandMockRecorder) Provide(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Provide", reflect.TypeOf((*MockDemand)(nil).Provide), arg0, arg1, arg2)
}

// RenderBidRequest mocks base method
func (_m *MockDemand) RenderBidRequest(_param0 context.Context, _param1 io.Writer, _param2 exchange.BidRequest) http.Header {
	ret := _m.ctrl.Call(_m, "RenderBidRequest", _param0, _param1, _param2)
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// RenderBidRequest indicates an expected call of RenderBidRequest
func (_mr *MockDemandMockRecorder) RenderBidRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "RenderBidRequest", reflect.TypeOf((*MockDemand)(nil).RenderBidRequest), arg0, arg1, arg2)
}

// Status mocks base method
func (_m *MockDemand) Status(_param0 context.Context, _param1 http.ResponseWriter, _param2 *http.Request) {
	_m.ctrl.Call(_m, "Status", _param0, _param1, _param2)
}

// Status indicates an expected call of Status
func (_mr *MockDemandMockRecorder) Status(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Status", reflect.TypeOf((*MockDemand)(nil).Status), arg0, arg1, arg2)
}

// TestMode mocks base method
func (_m *MockDemand) TestMode() bool {
	ret := _m.ctrl.Call(_m, "TestMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TestMode indicates an expected call of TestMode
func (_mr *MockDemandMockRecorder) TestMode() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "TestMode", reflect.TypeOf((*MockDemand)(nil).TestMode))
}

// Type mocks base method
func (_m *MockDemand) Type() exchange.DemandType {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(exchange.DemandType)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockDemandMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Type", reflect.TypeOf((*MockDemand)(nil).Type))
}

// WhiteListCountries mocks base method
func (_m *MockDemand) WhiteListCountries() []string {
	ret := _m.ctrl.Call(_m, "WhiteListCountries")
	ret0, _ := ret[0].([]string)
	return ret0
}

// WhiteListCountries indicates an expected call of WhiteListCountries
func (_mr *MockDemandMockRecorder) WhiteListCountries() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WhiteListCountries", reflect.TypeOf((*MockDemand)(nil).WhiteListCountries))
}

// Win mocks base method
func (_m *MockDemand) Win(_param0 context.Context, _param1 int64, _param2 string) {
	_m.ctrl.Call(_m, "Win", _param0, _param1, _param2)
}

// Win indicates an expected call of Win
func (_mr *MockDemandMockRecorder) Win(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Win", reflect.TypeOf((*MockDemand)(nil).Win), arg0, arg1, arg2)
}

// MockPublisher is a mock of Publisher interface
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockPublisher) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockPublisherMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockPublisher)(nil).Attributes))
}

// Cat mocks base method
func (_m *MockPublisher) Cat() []string {
	ret := _m.ctrl.Call(_m, "Cat")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Cat indicates an expected call of Cat
func (_mr *MockPublisherMockRecorder) Cat() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Cat", reflect.TypeOf((*MockPublisher)(nil).Cat))
}

// Domain mocks base method
func (_m *MockPublisher) Domain() string {
	ret := _m.ctrl.Call(_m, "Domain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Domain indicates an expected call of Domain
func (_mr *MockPublisherMockRecorder) Domain() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Domain", reflect.TypeOf((*MockPublisher)(nil).Domain))
}

// ID mocks base method
func (_m *MockPublisher) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockPublisherMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockPublisher)(nil).ID))
}

// Name mocks base method
func (_m *MockPublisher) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockPublisherMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockPublisher)(nil).Name))
}

// MockLocation is a mock of Location interface
type MockLocation struct {
	ctrl     *gomock.Controller
	recorder *MockLocationMockRecorder
}

// MockLocationMockRecorder is the mock recorder for MockLocation
type MockLocationMockRecorder struct {
	mock *MockLocation
}

// NewMockLocation creates a new mock instance
func NewMockLocation(ctrl *gomock.Controller) *MockLocation {
	mock := &MockLocation{ctrl: ctrl}
	mock.recorder = &MockLocationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockLocation) EXPECT() *MockLocationMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockLocation) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockLocationMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockLocation)(nil).Attributes))
}

// Country mocks base method
func (_m *MockLocation) Country() exchange.Country {
	ret := _m.ctrl.Call(_m, "Country")
	ret0, _ := ret[0].(exchange.Country)
	return ret0
}

// Country indicates an expected call of Country
func (_mr *MockLocationMockRecorder) Country() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Country", reflect.TypeOf((*MockLocation)(nil).Country))
}

// ISP mocks base method
func (_m *MockLocation) ISP() exchange.ISP {
	ret := _m.ctrl.Call(_m, "ISP")
	ret0, _ := ret[0].(exchange.ISP)
	return ret0
}

// ISP indicates an expected call of ISP
func (_mr *MockLocationMockRecorder) ISP() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ISP", reflect.TypeOf((*MockLocation)(nil).ISP))
}

// LatLon mocks base method
func (_m *MockLocation) LatLon() exchange.LatLon {
	ret := _m.ctrl.Call(_m, "LatLon")
	ret0, _ := ret[0].(exchange.LatLon)
	return ret0
}

// LatLon indicates an expected call of LatLon
func (_mr *MockLocationMockRecorder) LatLon() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "LatLon", reflect.TypeOf((*MockLocation)(nil).LatLon))
}

// Region mocks base method
func (_m *MockLocation) Region() exchange.Region {
	ret := _m.ctrl.Call(_m, "Region")
	ret0, _ := ret[0].(exchange.Region)
	return ret0
}

// Region indicates an expected call of Region
func (_mr *MockLocationMockRecorder) Region() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Region", reflect.TypeOf((*MockLocation)(nil).Region))
}

// MockSupplier is a mock of Supplier interface
type MockSupplier struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierMockRecorder
}

// MockSupplierMockRecorder is the mock recorder for MockSupplier
type MockSupplierMockRecorder struct {
	mock *MockSupplier
}

// NewMockSupplier creates a new mock instance
func NewMockSupplier(ctrl *gomock.Controller) *MockSupplier {
	mock := &MockSupplier{ctrl: ctrl}
	mock.recorder = &MockSupplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSupplier) EXPECT() *MockSupplierMockRecorder {
	return _m.recorder
}

// Currency mocks base method
func (_m *MockSupplier) Currency() string {
	ret := _m.ctrl.Call(_m, "Currency")
	ret0, _ := ret[0].(string)
	return ret0
}

// Currency indicates an expected call of Currency
func (_mr *MockSupplierMockRecorder) Currency() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Currency", reflect.TypeOf((*MockSupplier)(nil).Currency))
}

// ExcludedDemands mocks base method
func (_m *MockSupplier) ExcludedDemands() []string {
	ret := _m.ctrl.Call(_m, "ExcludedDemands")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ExcludedDemands indicates an expected call of ExcludedDemands
func (_mr *MockSupplierMockRecorder) ExcludedDemands() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ExcludedDemands", reflect.TypeOf((*MockSupplier)(nil).ExcludedDemands))
}

// FloorCPM mocks base method
func (_m *MockSupplier) FloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "FloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FloorCPM indicates an expected call of FloorCPM
func (_mr *MockSupplierMockRecorder) FloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FloorCPM", reflect.TypeOf((*MockSupplier)(nil).FloorCPM))
}

// GetBidRequest mocks base method
func (_m *MockSupplier) GetBidRequest(_param0 context.Context, _param1 *http.Request) (exchange.BidRequest, error) {
	ret := _m.ctrl.Call(_m, "GetBidRequest", _param0, _param1)
	ret0, _ := ret[0].(exchange.BidRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBidRequest indicates an expected call of GetBidRequest
func (_mr *MockSupplierMockRecorder) GetBidRequest(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetBidRequest", reflect.TypeOf((*MockSupplier)(nil).GetBidRequest), arg0, arg1)
}

// Name mocks base method
func (_m *MockSupplier) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockSupplierMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockSupplier)(nil).Name))
}

// RenderBidResponse mocks base method
func (_m *MockSupplier) RenderBidResponse(_param0 context.Context, _param1 io.Writer, _param2 exchange.BidResponse) http.Header {
	ret := _m.ctrl.Call(_m, "RenderBidResponse", _param0, _param1, _param2)
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// RenderBidResponse indicates an expected call of RenderBidResponse
func (_mr *MockSupplierMockRecorder) RenderBidResponse(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "RenderBidResponse", reflect.TypeOf((*MockSupplier)(nil).RenderBidResponse), arg0, arg1, arg2)
}

// Share mocks base method
func (_m *MockSupplier) Share() int {
	ret := _m.ctrl.Call(_m, "Share")
	ret0, _ := ret[0].(int)
	return ret0
}

// Share indicates an expected call of Share
func (_mr *MockSupplierMockRecorder) Share() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Share", reflect.TypeOf((*MockSupplier)(nil).Share))
}

// SoftFloorCPM mocks base method
func (_m *MockSupplier) SoftFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "SoftFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// SoftFloorCPM indicates an expected call of SoftFloorCPM
func (_mr *MockSupplierMockRecorder) SoftFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SoftFloorCPM", reflect.TypeOf((*MockSupplier)(nil).SoftFloorCPM))
}

// TestMode mocks base method
func (_m *MockSupplier) TestMode() bool {
	ret := _m.ctrl.Call(_m, "TestMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TestMode indicates an expected call of TestMode
func (_mr *MockSupplierMockRecorder) TestMode() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "TestMode", reflect.TypeOf((*MockSupplier)(nil).TestMode))
}

// Type mocks base method
func (_m *MockSupplier) Type() string {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockSupplierMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Type", reflect.TypeOf((*MockSupplier)(nil).Type))
}

// MockBidResponse is a mock of BidResponse interface
type MockBidResponse struct {
	ctrl     *gomock.Controller
	recorder *MockBidResponseMockRecorder
}

// MockBidResponseMockRecorder is the mock recorder for MockBidResponse
type MockBidResponseMockRecorder struct {
	mock *MockBidResponse
}

// NewMockBidResponse creates a new mock instance
func NewMockBidResponse(ctrl *gomock.Controller) *MockBidResponse {
	mock := &MockBidResponse{ctrl: ctrl}
	mock.recorder = &MockBidResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBidResponse) EXPECT() *MockBidResponseMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockBidResponse) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockBidResponseMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockBidResponse)(nil).Attributes))
}

// Bids mocks base method
func (_m *MockBidResponse) Bids() []exchange.Bid {
	ret := _m.ctrl.Call(_m, "Bids")
	ret0, _ := ret[0].([]exchange.Bid)
	return ret0
}

// Bids indicates an expected call of Bids
func (_mr *MockBidResponseMockRecorder) Bids() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Bids", reflect.TypeOf((*MockBidResponse)(nil).Bids))
}

// Excuse mocks base method
func (_m *MockBidResponse) Excuse() int {
	ret := _m.ctrl.Call(_m, "Excuse")
	ret0, _ := ret[0].(int)
	return ret0
}

// Excuse indicates an expected call of Excuse
func (_mr *MockBidResponseMockRecorder) Excuse() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Excuse", reflect.TypeOf((*MockBidResponse)(nil).Excuse))
}

// ID mocks base method
func (_m *MockBidResponse) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockBidResponseMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockBidResponse)(nil).ID))
}

// Supplier mocks base method
func (_m *MockBidResponse) Supplier() exchange.Supplier {
	ret := _m.ctrl.Call(_m, "Supplier")
	ret0, _ := ret[0].(exchange.Supplier)
	return ret0
}

// Supplier indicates an expected call of Supplier
func (_mr *MockBidResponseMockRecorder) Supplier() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Supplier", reflect.TypeOf((*MockBidResponse)(nil).Supplier))
}

// MockBid is a mock of Bid interface
type MockBid struct {
	ctrl     *gomock.Controller
	recorder *MockBidMockRecorder
}

// MockBidMockRecorder is the mock recorder for MockBid
type MockBidMockRecorder struct {
	mock *MockBid
}

// NewMockBid creates a new mock instance
func NewMockBid(ctrl *gomock.Controller) *MockBid {
	mock := &MockBid{ctrl: ctrl}
	mock.recorder = &MockBidMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBid) EXPECT() *MockBidMockRecorder {
	return _m.recorder
}

// AdDomains mocks base method
func (_m *MockBid) AdDomains() []string {
	ret := _m.ctrl.Call(_m, "AdDomains")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AdDomains indicates an expected call of AdDomains
func (_mr *MockBidMockRecorder) AdDomains() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdDomains", reflect.TypeOf((*MockBid)(nil).AdDomains))
}

// AdHeight mocks base method
func (_m *MockBid) AdHeight() int {
	ret := _m.ctrl.Call(_m, "AdHeight")
	ret0, _ := ret[0].(int)
	return ret0
}

// AdHeight indicates an expected call of AdHeight
func (_mr *MockBidMockRecorder) AdHeight() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdHeight", reflect.TypeOf((*MockBid)(nil).AdHeight))
}

// AdID mocks base method
func (_m *MockBid) AdID() string {
	ret := _m.ctrl.Call(_m, "AdID")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdID indicates an expected call of AdID
func (_mr *MockBidMockRecorder) AdID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdID", reflect.TypeOf((*MockBid)(nil).AdID))
}

// AdMarkup mocks base method
func (_m *MockBid) AdMarkup() string {
	ret := _m.ctrl.Call(_m, "AdMarkup")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdMarkup indicates an expected call of AdMarkup
func (_mr *MockBidMockRecorder) AdMarkup() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdMarkup", reflect.TypeOf((*MockBid)(nil).AdMarkup))
}

// AdWidth mocks base method
func (_m *MockBid) AdWidth() int {
	ret := _m.ctrl.Call(_m, "AdWidth")
	ret0, _ := ret[0].(int)
	return ret0
}

// AdWidth indicates an expected call of AdWidth
func (_mr *MockBidMockRecorder) AdWidth() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdWidth", reflect.TypeOf((*MockBid)(nil).AdWidth))
}

// Attributes mocks base method
func (_m *MockBid) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockBidMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockBid)(nil).Attributes))
}

// BillURL mocks base method
func (_m *MockBid) BillURL() string {
	ret := _m.ctrl.Call(_m, "BillURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BillURL indicates an expected call of BillURL
func (_mr *MockBidMockRecorder) BillURL() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BillURL", reflect.TypeOf((*MockBid)(nil).BillURL))
}

// Categories mocks base method
func (_m *MockBid) Categories() []string {
	ret := _m.ctrl.Call(_m, "Categories")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Categories indicates an expected call of Categories
func (_mr *MockBidMockRecorder) Categories() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Categories", reflect.TypeOf((*MockBid)(nil).Categories))
}

// Demand mocks base method
func (_m *MockBid) Demand() exchange.Demand {
	ret := _m.ctrl.Call(_m, "Demand")
	ret0, _ := ret[0].(exchange.Demand)
	return ret0
}

// Demand indicates an expected call of Demand
func (_mr *MockBidMockRecorder) Demand() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Demand", reflect.TypeOf((*MockBid)(nil).Demand))
}

// ID mocks base method
func (_m *MockBid) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockBidMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockBid)(nil).ID))
}

// ImpID mocks base method
func (_m *MockBid) ImpID() string {
	ret := _m.ctrl.Call(_m, "ImpID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ImpID indicates an expected call of ImpID
func (_mr *MockBidMockRecorder) ImpID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ImpID", reflect.TypeOf((*MockBid)(nil).ImpID))
}

// Price mocks base method
func (_m *MockBid) Price() int64 {
	ret := _m.ctrl.Call(_m, "Price")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Price indicates an expected call of Price
func (_mr *MockBidMockRecorder) Price() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Price", reflect.TypeOf((*MockBid)(nil).Price))
}

// WinURL mocks base method
func (_m *MockBid) WinURL() string {
	ret := _m.ctrl.Call(_m, "WinURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// WinURL indicates an expected call of WinURL
func (_mr *MockBidMockRecorder) WinURL() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WinURL", reflect.TypeOf((*MockBid)(nil).WinURL))
}

// MockAdDetail is a mock of AdDetail interface
type MockAdDetail struct {
	ctrl     *gomock.Controller
	recorder *MockAdDetailMockRecorder
}

// MockAdDetailMockRecorder is the mock recorder for MockAdDetail
type MockAdDetailMockRecorder struct {
	mock *MockAdDetail
}

// NewMockAdDetail creates a new mock instance
func NewMockAdDetail(ctrl *gomock.Controller) *MockAdDetail {
	mock := &MockAdDetail{ctrl: ctrl}
	mock.recorder = &MockAdDetailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockAdDetail) EXPECT() *MockAdDetailMockRecorder {
	return _m.recorder
}

// AdDomains mocks base method
func (_m *MockAdDetail) AdDomains() []string {
	ret := _m.ctrl.Call(_m, "AdDomains")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AdDomains indicates an expected call of AdDomains
func (_mr *MockAdDetailMockRecorder) AdDomains() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdDomains", reflect.TypeOf((*MockAdDetail)(nil).AdDomains))
}

// AdHeight mocks base method
func (_m *MockAdDetail) AdHeight() int {
	ret := _m.ctrl.Call(_m, "AdHeight")
	ret0, _ := ret[0].(int)
	return ret0
}

// AdHeight indicates an expected call of AdHeight
func (_mr *MockAdDetailMockRecorder) AdHeight() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdHeight", reflect.TypeOf((*MockAdDetail)(nil).AdHeight))
}

// AdID mocks base method
func (_m *MockAdDetail) AdID() string {
	ret := _m.ctrl.Call(_m, "AdID")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdID indicates an expected call of AdID
func (_mr *MockAdDetailMockRecorder) AdID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdID", reflect.TypeOf((*MockAdDetail)(nil).AdID))
}

// AdMarkup mocks base method
func (_m *MockAdDetail) AdMarkup() string {
	ret := _m.ctrl.Call(_m, "AdMarkup")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdMarkup indicates an expected call of AdMarkup
func (_mr *MockAdDetailMockRecorder) AdMarkup() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdMarkup", reflect.TypeOf((*MockAdDetail)(nil).AdMarkup))
}

// AdWidth mocks base method
func (_m *MockAdDetail) AdWidth() int {
	ret := _m.ctrl.Call(_m, "AdWidth")
	ret0, _ := ret[0].(int)
	return ret0
}

// AdWidth indicates an expected call of AdWidth
func (_mr *MockAdDetailMockRecorder) AdWidth() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdWidth", reflect.TypeOf((*MockAdDetail)(nil).AdWidth))
}

// MockBidRequest is a mock of BidRequest interface
type MockBidRequest struct {
	ctrl     *gomock.Controller
	recorder *MockBidRequestMockRecorder
}

// MockBidRequestMockRecorder is the mock recorder for MockBidRequest
type MockBidRequestMockRecorder struct {
	mock *MockBidRequest
}

// NewMockBidRequest creates a new mock instance
func NewMockBidRequest(ctrl *gomock.Controller) *MockBidRequest {
	mock := &MockBidRequest{ctrl: ctrl}
	mock.recorder = &MockBidRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBidRequest) EXPECT() *MockBidRequestMockRecorder {
	return _m.recorder
}

// AllowedLanguage mocks base method
func (_m *MockBidRequest) AllowedLanguage() []string {
	ret := _m.ctrl.Call(_m, "AllowedLanguage")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AllowedLanguage indicates an expected call of AllowedLanguage
func (_mr *MockBidRequestMockRecorder) AllowedLanguage() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AllowedLanguage", reflect.TypeOf((*MockBidRequest)(nil).AllowedLanguage))
}

// Attributes mocks base method
func (_m *MockBidRequest) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockBidRequestMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockBidRequest)(nil).Attributes))
}

// AuctionType mocks base method
func (_m *MockBidRequest) AuctionType() exchange.AuctionType {
	ret := _m.ctrl.Call(_m, "AuctionType")
	ret0, _ := ret[0].(exchange.AuctionType)
	return ret0
}

// AuctionType indicates an expected call of AuctionType
func (_mr *MockBidRequestMockRecorder) AuctionType() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AuctionType", reflect.TypeOf((*MockBidRequest)(nil).AuctionType))
}

// BlackList mocks base method
func (_m *MockBidRequest) BlackList() []string {
	ret := _m.ctrl.Call(_m, "BlackList")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BlackList indicates an expected call of BlackList
func (_mr *MockBidRequestMockRecorder) BlackList() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlackList", reflect.TypeOf((*MockBidRequest)(nil).BlackList))
}

// BlockedAdvertiserDomain mocks base method
func (_m *MockBidRequest) BlockedAdvertiserDomain() []string {
	ret := _m.ctrl.Call(_m, "BlockedAdvertiserDomain")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BlockedAdvertiserDomain indicates an expected call of BlockedAdvertiserDomain
func (_mr *MockBidRequestMockRecorder) BlockedAdvertiserDomain() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlockedAdvertiserDomain", reflect.TypeOf((*MockBidRequest)(nil).BlockedAdvertiserDomain))
}

// BlockedCategories mocks base method
func (_m *MockBidRequest) BlockedCategories() []string {
	ret := _m.ctrl.Call(_m, "BlockedCategories")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BlockedCategories indicates an expected call of BlockedCategories
func (_mr *MockBidRequestMockRecorder) BlockedCategories() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlockedCategories", reflect.TypeOf((*MockBidRequest)(nil).BlockedCategories))
}

// CID mocks base method
func (_m *MockBidRequest) CID() string {
	ret := _m.ctrl.Call(_m, "CID")
	ret0, _ := ret[0].(string)
	return ret0
}

// CID indicates an expected call of CID
func (_mr *MockBidRequestMockRecorder) CID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CID", reflect.TypeOf((*MockBidRequest)(nil).CID))
}

// Device mocks base method
func (_m *MockBidRequest) Device() exchange.Device {
	ret := _m.ctrl.Call(_m, "Device")
	ret0, _ := ret[0].(exchange.Device)
	return ret0
}

// Device indicates an expected call of Device
func (_mr *MockBidRequestMockRecorder) Device() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Device", reflect.TypeOf((*MockBidRequest)(nil).Device))
}

// ID mocks base method
func (_m *MockBidRequest) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockBidRequestMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockBidRequest)(nil).ID))
}

// Imp mocks base method
func (_m *MockBidRequest) Imp() []exchange.Impression {
	ret := _m.ctrl.Call(_m, "Imp")
	ret0, _ := ret[0].([]exchange.Impression)
	return ret0
}

// Imp indicates an expected call of Imp
func (_mr *MockBidRequestMockRecorder) Imp() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Imp", reflect.TypeOf((*MockBidRequest)(nil).Imp))
}

// Inventory mocks base method
func (_m *MockBidRequest) Inventory() exchange.Inventory {
	ret := _m.ctrl.Call(_m, "Inventory")
	ret0, _ := ret[0].(exchange.Inventory)
	return ret0
}

// Inventory indicates an expected call of Inventory
func (_mr *MockBidRequestMockRecorder) Inventory() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Inventory", reflect.TypeOf((*MockBidRequest)(nil).Inventory))
}

// Request mocks base method
func (_m *MockBidRequest) Request() *http.Request {
	ret := _m.ctrl.Call(_m, "Request")
	ret0, _ := ret[0].(*http.Request)
	return ret0
}

// Request indicates an expected call of Request
func (_mr *MockBidRequestMockRecorder) Request() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Request", reflect.TypeOf((*MockBidRequest)(nil).Request))
}

// TMax mocks base method
func (_m *MockBidRequest) TMax() time.Duration {
	ret := _m.ctrl.Call(_m, "TMax")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TMax indicates an expected call of TMax
func (_mr *MockBidRequestMockRecorder) TMax() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "TMax", reflect.TypeOf((*MockBidRequest)(nil).TMax))
}

// Test mocks base method
func (_m *MockBidRequest) Test() bool {
	ret := _m.ctrl.Call(_m, "Test")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Test indicates an expected call of Test
func (_mr *MockBidRequestMockRecorder) Test() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Test", reflect.TypeOf((*MockBidRequest)(nil).Test))
}

// Time mocks base method
func (_m *MockBidRequest) Time() time.Time {
	ret := _m.ctrl.Call(_m, "Time")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Time indicates an expected call of Time
func (_mr *MockBidRequestMockRecorder) Time() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Time", reflect.TypeOf((*MockBidRequest)(nil).Time))
}

// User mocks base method
func (_m *MockBidRequest) User() exchange.User {
	ret := _m.ctrl.Call(_m, "User")
	ret0, _ := ret[0].(exchange.User)
	return ret0
}

// User indicates an expected call of User
func (_mr *MockBidRequestMockRecorder) User() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "User", reflect.TypeOf((*MockBidRequest)(nil).User))
}

// WhiteList mocks base method
func (_m *MockBidRequest) WhiteList() []string {
	ret := _m.ctrl.Call(_m, "WhiteList")
	ret0, _ := ret[0].([]string)
	return ret0
}

// WhiteList indicates an expected call of WhiteList
func (_mr *MockBidRequestMockRecorder) WhiteList() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WhiteList", reflect.TypeOf((*MockBidRequest)(nil).WhiteList))
}

// MockBanner is a mock of Banner interface
type MockBanner struct {
	ctrl     *gomock.Controller
	recorder *MockBannerMockRecorder
}

// MockBannerMockRecorder is the mock recorder for MockBanner
type MockBannerMockRecorder struct {
	mock *MockBanner
}

// NewMockBanner creates a new mock instance
func NewMockBanner(ctrl *gomock.Controller) *MockBanner {
	mock := &MockBanner{ctrl: ctrl}
	mock.recorder = &MockBannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBanner) EXPECT() *MockBannerMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockBanner) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockBannerMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockBanner)(nil).Attributes))
}

// BlockedAttributes mocks base method
func (_m *MockBanner) BlockedAttributes() []exchange.CreativeAttribute {
	ret := _m.ctrl.Call(_m, "BlockedAttributes")
	ret0, _ := ret[0].([]exchange.CreativeAttribute)
	return ret0
}

// BlockedAttributes indicates an expected call of BlockedAttributes
func (_mr *MockBannerMockRecorder) BlockedAttributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlockedAttributes", reflect.TypeOf((*MockBanner)(nil).BlockedAttributes))
}

// BlockedTypes mocks base method
func (_m *MockBanner) BlockedTypes() []exchange.BannerType {
	ret := _m.ctrl.Call(_m, "BlockedTypes")
	ret0, _ := ret[0].([]exchange.BannerType)
	return ret0
}

// BlockedTypes indicates an expected call of BlockedTypes
func (_mr *MockBannerMockRecorder) BlockedTypes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlockedTypes", reflect.TypeOf((*MockBanner)(nil).BlockedTypes))
}

// Height mocks base method
func (_m *MockBanner) Height() int {
	ret := _m.ctrl.Call(_m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height
func (_mr *MockBannerMockRecorder) Height() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Height", reflect.TypeOf((*MockBanner)(nil).Height))
}

// ID mocks base method
func (_m *MockBanner) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockBannerMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockBanner)(nil).ID))
}

// Mimes mocks base method
func (_m *MockBanner) Mimes() []string {
	ret := _m.ctrl.Call(_m, "Mimes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Mimes indicates an expected call of Mimes
func (_mr *MockBannerMockRecorder) Mimes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Mimes", reflect.TypeOf((*MockBanner)(nil).Mimes))
}

// Width mocks base method
func (_m *MockBanner) Width() int {
	ret := _m.ctrl.Call(_m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width
func (_mr *MockBannerMockRecorder) Width() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Width", reflect.TypeOf((*MockBanner)(nil).Width))
}

// MockDevice is a mock of Device interface
type MockDevice struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceMockRecorder
}

// MockDeviceMockRecorder is the mock recorder for MockDevice
type MockDeviceMockRecorder struct {
	mock *MockDevice
}

// NewMockDevice creates a new mock instance
func NewMockDevice(ctrl *gomock.Controller) *MockDevice {
	mock := &MockDevice{ctrl: ctrl}
	mock.recorder = &MockDeviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockDevice) EXPECT() *MockDeviceMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockDevice) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockDeviceMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockDevice)(nil).Attributes))
}

// CID mocks base method
func (_m *MockDevice) CID() string {
	ret := _m.ctrl.Call(_m, "CID")
	ret0, _ := ret[0].(string)
	return ret0
}

// CID indicates an expected call of CID
func (_mr *MockDeviceMockRecorder) CID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CID", reflect.TypeOf((*MockDevice)(nil).CID))
}

// Carrier mocks base method
func (_m *MockDevice) Carrier() string {
	ret := _m.ctrl.Call(_m, "Carrier")
	ret0, _ := ret[0].(string)
	return ret0
}

// Carrier indicates an expected call of Carrier
func (_mr *MockDeviceMockRecorder) Carrier() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Carrier", reflect.TypeOf((*MockDevice)(nil).Carrier))
}

// ConnType mocks base method
func (_m *MockDevice) ConnType() exchange.ConnectionType {
	ret := _m.ctrl.Call(_m, "ConnType")
	ret0, _ := ret[0].(exchange.ConnectionType)
	return ret0
}

// ConnType indicates an expected call of ConnType
func (_mr *MockDeviceMockRecorder) ConnType() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ConnType", reflect.TypeOf((*MockDevice)(nil).ConnType))
}

// DeviceType mocks base method
func (_m *MockDevice) DeviceType() exchange.DeviceType {
	ret := _m.ctrl.Call(_m, "DeviceType")
	ret0, _ := ret[0].(exchange.DeviceType)
	return ret0
}

// DeviceType indicates an expected call of DeviceType
func (_mr *MockDeviceMockRecorder) DeviceType() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DeviceType", reflect.TypeOf((*MockDevice)(nil).DeviceType))
}

// Geo mocks base method
func (_m *MockDevice) Geo() exchange.Geo {
	ret := _m.ctrl.Call(_m, "Geo")
	ret0, _ := ret[0].(exchange.Geo)
	return ret0
}

// Geo indicates an expected call of Geo
func (_mr *MockDeviceMockRecorder) Geo() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Geo", reflect.TypeOf((*MockDevice)(nil).Geo))
}

// IP mocks base method
func (_m *MockDevice) IP() string {
	ret := _m.ctrl.Call(_m, "IP")
	ret0, _ := ret[0].(string)
	return ret0
}

// IP indicates an expected call of IP
func (_mr *MockDeviceMockRecorder) IP() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IP", reflect.TypeOf((*MockDevice)(nil).IP))
}

// LAC mocks base method
func (_m *MockDevice) LAC() string {
	ret := _m.ctrl.Call(_m, "LAC")
	ret0, _ := ret[0].(string)
	return ret0
}

// LAC indicates an expected call of LAC
func (_mr *MockDeviceMockRecorder) LAC() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "LAC", reflect.TypeOf((*MockDevice)(nil).LAC))
}

// Language mocks base method
func (_m *MockDevice) Language() string {
	ret := _m.ctrl.Call(_m, "Language")
	ret0, _ := ret[0].(string)
	return ret0
}

// Language indicates an expected call of Language
func (_mr *MockDeviceMockRecorder) Language() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Language", reflect.TypeOf((*MockDevice)(nil).Language))
}

// MCC mocks base method
func (_m *MockDevice) MCC() string {
	ret := _m.ctrl.Call(_m, "MCC")
	ret0, _ := ret[0].(string)
	return ret0
}

// MCC indicates an expected call of MCC
func (_mr *MockDeviceMockRecorder) MCC() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "MCC", reflect.TypeOf((*MockDevice)(nil).MCC))
}

// MNC mocks base method
func (_m *MockDevice) MNC() string {
	ret := _m.ctrl.Call(_m, "MNC")
	ret0, _ := ret[0].(string)
	return ret0
}

// MNC indicates an expected call of MNC
func (_mr *MockDeviceMockRecorder) MNC() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "MNC", reflect.TypeOf((*MockDevice)(nil).MNC))
}

// Make mocks base method
func (_m *MockDevice) Make() string {
	ret := _m.ctrl.Call(_m, "Make")
	ret0, _ := ret[0].(string)
	return ret0
}

// Make indicates an expected call of Make
func (_mr *MockDeviceMockRecorder) Make() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Make", reflect.TypeOf((*MockDevice)(nil).Make))
}

// Model mocks base method
func (_m *MockDevice) Model() string {
	ret := _m.ctrl.Call(_m, "Model")
	ret0, _ := ret[0].(string)
	return ret0
}

// Model indicates an expected call of Model
func (_mr *MockDeviceMockRecorder) Model() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Model", reflect.TypeOf((*MockDevice)(nil).Model))
}

// OS mocks base method
func (_m *MockDevice) OS() string {
	ret := _m.ctrl.Call(_m, "OS")
	ret0, _ := ret[0].(string)
	return ret0
}

// OS indicates an expected call of OS
func (_mr *MockDeviceMockRecorder) OS() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "OS", reflect.TypeOf((*MockDevice)(nil).OS))
}

// UserAgent mocks base method
func (_m *MockDevice) UserAgent() string {
	ret := _m.ctrl.Call(_m, "UserAgent")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserAgent indicates an expected call of UserAgent
func (_mr *MockDeviceMockRecorder) UserAgent() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UserAgent", reflect.TypeOf((*MockDevice)(nil).UserAgent))
}

// MockInventory is a mock of Inventory interface
type MockInventory struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryMockRecorder
}

// MockInventoryMockRecorder is the mock recorder for MockInventory
type MockInventoryMockRecorder struct {
	mock *MockInventory
}

// NewMockInventory creates a new mock instance
func NewMockInventory(ctrl *gomock.Controller) *MockInventory {
	mock := &MockInventory{ctrl: ctrl}
	mock.recorder = &MockInventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockInventory) EXPECT() *MockInventoryMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockInventory) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockInventoryMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockInventory)(nil).Attributes))
}

// Cat mocks base method
func (_m *MockInventory) Cat() []exchange.Category {
	ret := _m.ctrl.Call(_m, "Cat")
	ret0, _ := ret[0].([]exchange.Category)
	return ret0
}

// Cat indicates an expected call of Cat
func (_mr *MockInventoryMockRecorder) Cat() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Cat", reflect.TypeOf((*MockInventory)(nil).Cat))
}

// Domain mocks base method
func (_m *MockInventory) Domain() string {
	ret := _m.ctrl.Call(_m, "Domain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Domain indicates an expected call of Domain
func (_mr *MockInventoryMockRecorder) Domain() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Domain", reflect.TypeOf((*MockInventory)(nil).Domain))
}

// FloorCPM mocks base method
func (_m *MockInventory) FloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "FloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FloorCPM indicates an expected call of FloorCPM
func (_mr *MockInventoryMockRecorder) FloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FloorCPM", reflect.TypeOf((*MockInventory)(nil).FloorCPM))
}

// ID mocks base method
func (_m *MockInventory) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockInventoryMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockInventory)(nil).ID))
}

// Name mocks base method
func (_m *MockInventory) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockInventoryMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockInventory)(nil).Name))
}

// Publisher mocks base method
func (_m *MockInventory) Publisher() exchange.Publisher {
	ret := _m.ctrl.Call(_m, "Publisher")
	ret0, _ := ret[0].(exchange.Publisher)
	return ret0
}

// Publisher indicates an expected call of Publisher
func (_mr *MockInventoryMockRecorder) Publisher() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Publisher", reflect.TypeOf((*MockInventory)(nil).Publisher))
}

// SoftFloorCPM mocks base method
func (_m *MockInventory) SoftFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "SoftFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// SoftFloorCPM indicates an expected call of SoftFloorCPM
func (_mr *MockInventoryMockRecorder) SoftFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SoftFloorCPM", reflect.TypeOf((*MockInventory)(nil).SoftFloorCPM))
}

// Supplier mocks base method
func (_m *MockInventory) Supplier() exchange.Supplier {
	ret := _m.ctrl.Call(_m, "Supplier")
	ret0, _ := ret[0].(exchange.Supplier)
	return ret0
}

// Supplier indicates an expected call of Supplier
func (_mr *MockInventoryMockRecorder) Supplier() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Supplier", reflect.TypeOf((*MockInventory)(nil).Supplier))
}

// MockSite is a mock of Site interface
type MockSite struct {
	ctrl     *gomock.Controller
	recorder *MockSiteMockRecorder
}

// MockSiteMockRecorder is the mock recorder for MockSite
type MockSiteMockRecorder struct {
	mock *MockSite
}

// NewMockSite creates a new mock instance
func NewMockSite(ctrl *gomock.Controller) *MockSite {
	mock := &MockSite{ctrl: ctrl}
	mock.recorder = &MockSiteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSite) EXPECT() *MockSiteMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockSite) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockSiteMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockSite)(nil).Attributes))
}

// Cat mocks base method
func (_m *MockSite) Cat() []exchange.Category {
	ret := _m.ctrl.Call(_m, "Cat")
	ret0, _ := ret[0].([]exchange.Category)
	return ret0
}

// Cat indicates an expected call of Cat
func (_mr *MockSiteMockRecorder) Cat() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Cat", reflect.TypeOf((*MockSite)(nil).Cat))
}

// Domain mocks base method
func (_m *MockSite) Domain() string {
	ret := _m.ctrl.Call(_m, "Domain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Domain indicates an expected call of Domain
func (_mr *MockSiteMockRecorder) Domain() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Domain", reflect.TypeOf((*MockSite)(nil).Domain))
}

// FloorCPM mocks base method
func (_m *MockSite) FloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "FloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FloorCPM indicates an expected call of FloorCPM
func (_mr *MockSiteMockRecorder) FloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FloorCPM", reflect.TypeOf((*MockSite)(nil).FloorCPM))
}

// ID mocks base method
func (_m *MockSite) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockSiteMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockSite)(nil).ID))
}

// Name mocks base method
func (_m *MockSite) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockSiteMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockSite)(nil).Name))
}

// Page mocks base method
func (_m *MockSite) Page() string {
	ret := _m.ctrl.Call(_m, "Page")
	ret0, _ := ret[0].(string)
	return ret0
}

// Page indicates an expected call of Page
func (_mr *MockSiteMockRecorder) Page() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Page", reflect.TypeOf((*MockSite)(nil).Page))
}

// Publisher mocks base method
func (_m *MockSite) Publisher() exchange.Publisher {
	ret := _m.ctrl.Call(_m, "Publisher")
	ret0, _ := ret[0].(exchange.Publisher)
	return ret0
}

// Publisher indicates an expected call of Publisher
func (_mr *MockSiteMockRecorder) Publisher() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Publisher", reflect.TypeOf((*MockSite)(nil).Publisher))
}

// Ref mocks base method
func (_m *MockSite) Ref() string {
	ret := _m.ctrl.Call(_m, "Ref")
	ret0, _ := ret[0].(string)
	return ret0
}

// Ref indicates an expected call of Ref
func (_mr *MockSiteMockRecorder) Ref() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Ref", reflect.TypeOf((*MockSite)(nil).Ref))
}

// SoftFloorCPM mocks base method
func (_m *MockSite) SoftFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "SoftFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// SoftFloorCPM indicates an expected call of SoftFloorCPM
func (_mr *MockSiteMockRecorder) SoftFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SoftFloorCPM", reflect.TypeOf((*MockSite)(nil).SoftFloorCPM))
}

// Supplier mocks base method
func (_m *MockSite) Supplier() exchange.Supplier {
	ret := _m.ctrl.Call(_m, "Supplier")
	ret0, _ := ret[0].(exchange.Supplier)
	return ret0
}

// Supplier indicates an expected call of Supplier
func (_mr *MockSiteMockRecorder) Supplier() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Supplier", reflect.TypeOf((*MockSite)(nil).Supplier))
}

// MockApp is a mock of App interface
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
}

// MockAppMockRecorder is the mock recorder for MockApp
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockApp) EXPECT() *MockAppMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockApp) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockAppMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockApp)(nil).Attributes))
}

// Bundle mocks base method
func (_m *MockApp) Bundle() string {
	ret := _m.ctrl.Call(_m, "Bundle")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bundle indicates an expected call of Bundle
func (_mr *MockAppMockRecorder) Bundle() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Bundle", reflect.TypeOf((*MockApp)(nil).Bundle))
}

// Cat mocks base method
func (_m *MockApp) Cat() []exchange.Category {
	ret := _m.ctrl.Call(_m, "Cat")
	ret0, _ := ret[0].([]exchange.Category)
	return ret0
}

// Cat indicates an expected call of Cat
func (_mr *MockAppMockRecorder) Cat() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Cat", reflect.TypeOf((*MockApp)(nil).Cat))
}

// Domain mocks base method
func (_m *MockApp) Domain() string {
	ret := _m.ctrl.Call(_m, "Domain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Domain indicates an expected call of Domain
func (_mr *MockAppMockRecorder) Domain() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Domain", reflect.TypeOf((*MockApp)(nil).Domain))
}

// FloorCPM mocks base method
func (_m *MockApp) FloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "FloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FloorCPM indicates an expected call of FloorCPM
func (_mr *MockAppMockRecorder) FloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FloorCPM", reflect.TypeOf((*MockApp)(nil).FloorCPM))
}

// ID mocks base method
func (_m *MockApp) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockAppMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockApp)(nil).ID))
}

// Name mocks base method
func (_m *MockApp) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockAppMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockApp)(nil).Name))
}

// Publisher mocks base method
func (_m *MockApp) Publisher() exchange.Publisher {
	ret := _m.ctrl.Call(_m, "Publisher")
	ret0, _ := ret[0].(exchange.Publisher)
	return ret0
}

// Publisher indicates an expected call of Publisher
func (_mr *MockAppMockRecorder) Publisher() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Publisher", reflect.TypeOf((*MockApp)(nil).Publisher))
}

// SoftFloorCPM mocks base method
func (_m *MockApp) SoftFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "SoftFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// SoftFloorCPM indicates an expected call of SoftFloorCPM
func (_mr *MockAppMockRecorder) SoftFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SoftFloorCPM", reflect.TypeOf((*MockApp)(nil).SoftFloorCPM))
}

// Supplier mocks base method
func (_m *MockApp) Supplier() exchange.Supplier {
	ret := _m.ctrl.Call(_m, "Supplier")
	ret0, _ := ret[0].(exchange.Supplier)
	return ret0
}

// Supplier indicates an expected call of Supplier
func (_mr *MockAppMockRecorder) Supplier() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Supplier", reflect.TypeOf((*MockApp)(nil).Supplier))
}

// MockNative is a mock of Native interface
type MockNative struct {
	ctrl     *gomock.Controller
	recorder *MockNativeMockRecorder
}

// MockNativeMockRecorder is the mock recorder for MockNative
type MockNativeMockRecorder struct {
	mock *MockNative
}

// NewMockNative creates a new mock instance
func NewMockNative(ctrl *gomock.Controller) *MockNative {
	mock := &MockNative{ctrl: ctrl}
	mock.recorder = &MockNativeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockNative) EXPECT() *MockNativeMockRecorder {
	return _m.recorder
}

// AdLength mocks base method
func (_m *MockNative) AdLength() int {
	ret := _m.ctrl.Call(_m, "AdLength")
	ret0, _ := ret[0].(int)
	return ret0
}

// AdLength indicates an expected call of AdLength
func (_mr *MockNativeMockRecorder) AdLength() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AdLength", reflect.TypeOf((*MockNative)(nil).AdLength))
}

// Attributes mocks base method
func (_m *MockNative) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockNativeMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockNative)(nil).Attributes))
}

// IsExtValid mocks base method
func (_m *MockNative) IsExtValid() bool {
	ret := _m.ctrl.Call(_m, "IsExtValid")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExtValid indicates an expected call of IsExtValid
func (_mr *MockNativeMockRecorder) IsExtValid() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IsExtValid", reflect.TypeOf((*MockNative)(nil).IsExtValid))
}

// Request mocks base method
func (_m *MockNative) Request() []byte {
	ret := _m.ctrl.Call(_m, "Request")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Request indicates an expected call of Request
func (_mr *MockNativeMockRecorder) Request() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Request", reflect.TypeOf((*MockNative)(nil).Request))
}

// MockUser is a mock of User interface
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockUser) EXPECT() *MockUserMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockUser) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockUserMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockUser)(nil).Attributes))
}

// ID mocks base method
func (_m *MockUser) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockUserMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ID", reflect.TypeOf((*MockUser)(nil).ID))
}

// MockVideo is a mock of Video interface
type MockVideo struct {
	ctrl     *gomock.Controller
	recorder *MockVideoMockRecorder
}

// MockVideoMockRecorder is the mock recorder for MockVideo
type MockVideoMockRecorder struct {
	mock *MockVideo
}

// NewMockVideo creates a new mock instance
func NewMockVideo(ctrl *gomock.Controller) *MockVideo {
	mock := &MockVideo{ctrl: ctrl}
	mock.recorder = &MockVideoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockVideo) EXPECT() *MockVideoMockRecorder {
	return _m.recorder
}

// Attributes mocks base method
func (_m *MockVideo) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockVideoMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Attributes", reflect.TypeOf((*MockVideo)(nil).Attributes))
}

// BlockedAttributes mocks base method
func (_m *MockVideo) BlockedAttributes() []exchange.CreativeAttribute {
	ret := _m.ctrl.Call(_m, "BlockedAttributes")
	ret0, _ := ret[0].([]exchange.CreativeAttribute)
	return ret0
}

// BlockedAttributes indicates an expected call of BlockedAttributes
func (_mr *MockVideoMockRecorder) BlockedAttributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlockedAttributes", reflect.TypeOf((*MockVideo)(nil).BlockedAttributes))
}

// Height mocks base method
func (_m *MockVideo) Height() int {
	ret := _m.ctrl.Call(_m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height
func (_mr *MockVideoMockRecorder) Height() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Height", reflect.TypeOf((*MockVideo)(nil).Height))
}

// Linearity mocks base method
func (_m *MockVideo) Linearity() bool {
	ret := _m.ctrl.Call(_m, "Linearity")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Linearity indicates an expected call of Linearity
func (_mr *MockVideoMockRecorder) Linearity() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Linearity", reflect.TypeOf((*MockVideo)(nil).Linearity))
}

// Mimes mocks base method
func (_m *MockVideo) Mimes() []string {
	ret := _m.ctrl.Call(_m, "Mimes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Mimes indicates an expected call of Mimes
func (_mr *MockVideoMockRecorder) Mimes() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Mimes", reflect.TypeOf((*MockVideo)(nil).Mimes))
}

// Width mocks base method
func (_m *MockVideo) Width() int {
	ret := _m.ctrl.Call(_m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width
func (_mr *MockVideoMockRecorder) Width() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Width", reflect.TypeOf((*MockVideo)(nil).Width))
}
